snakefile: workflow/Snakefile
use-conda: True
conda-frontend: mamba
rerun-incomplete: True
jobs: 5
latency-wait: 120
keep-going: True
configfile: inputs/config.yaml
keep-incomplete: True
# unlock: True

cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.tasks}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name={rule}-%j
    --output="logs/{rule}/{wildcards}.out"
    --error="logs/{rule}/{wildcards}.err"

default-resources:
  - time="1-0"
  - partition="sched_mit_chisholm"
  - mem=50000  # 50G 
  - tasks=1  # always 1
  - cpus_per_task=1

# set-resources:
set-resources:
  # multi-threaded rules
  - run_trim_PE:cpus_per_task=10
  - read_mapping:cpus_per_task=10

  # memory intensive rules
  - run_trim_PE:mem=100000  # 100G 
